### ISSUE TITLE
3.6 Compatibility

### ISSUE THREAD

**Issue by maxbucknell** [tPl0ch/puppet-composer#46]
In the README, it says compatibility with puppet < 3.5.

Is this module known to not work with Puppet? Why not? What kind of work would have to be done?

**Comment by tPl0ch** [comment]
@maxbucknell This actually works with all Puppet versions since 2.7, closing this.

**Comment by scottsb** [comment]
@tPl0ch Will you update the README to indicate this compatibility? I came upon this issue with the same question.
