### ISSUE TITLE
Augeas[whitelist_phar]: Could not evaluate

### ISSUE THREAD

**Issue by bitgandtter** [tPl0ch/puppet-composer#53]
Hello, im using your module on my Vagrant-Puppet configuration.

I have puppet Puppet v3.4.3
Vagrant 1.6.3

configuration on my manifest

class { 'composer':
    target_dir      => '/usr/local/bin',
    composer_file   => 'composer', # could also be 'composer.phar'
  }

  composer::selfupdate { 'selfupdate_composer':
    timeout       => 300,   # Timeout for this command
    tries         => 3,     # Retries for this command
  }

  composer::exec { 'project-update':
    cmd => 'update',  # REQUIRED
    cwd => '/var/www', # REQUIRED
  }

i get this error:

Error: /Stage[main]/Composer/Augeas[whitelist_phar]: Could not evaluate: Save failed with return code false, see debug
Warning: /Stage[main]/Composer/Exec[download_composer]: Skipping because of failed dependencies
Warning: /Stage[main]/Composer/File[/usr/local/bin/composer]: Skipping because of failed dependencies
Warning: /Stage[main]/Php/Composer::Exec[project-update]/Exec[composer_update_project-update]: Skipping because of failed dependencies
Warning: /Stage[main]/Php/Composer::Selfupdate[selfupdate_composer]/Exec[composer_selfupdate_selfupdate_composer]: Skipping because of failed dependencies

In the documentation reads that wont require augeas but its installed by default on ubuntu OS 14.04

**Comment by andyshinn** [comment]
A pull request was merged which fixes the `suhosin_enabled` on Ubuntu 14.04: https://github.com/tPl0ch/puppet-composer/pull/59. We released module version 1.3.4 that contains the fix. Please let us know if still not working.
