### ISSUE TITLE
"composer install" always runs in dev mode

### ISSUE THREAD

**Issue by talisto** [tPl0ch/puppet-composer#68]
the `install.erb` template has this line:

```
<% if @dev %> --dev<% end -%>
```

however, `--dev` defaults to `on` for the `install` command now, so there's no way to actually disable dev mode for installs.  I noticed the `update.erb` has the following line:

```
<% unless @dev %> --no-dev<% end -%>
```
that should be copied over to the `install.erb` as well.

**Comment by tPl0ch** [comment]
@talisto Yes you are totally right. Weird that we missed this. I will add this fix to the 2.0 release which will be due this weekend.

Thanks for reporting!
