### ISSUE TITLE
Forge package includes spec submodules

### ISSUE THREAD

**Issue by scottsb** [tPl0ch/puppet-composer#73]
The current Forge copy of this module includes the contents of your `modules/` and `spec/fixtues/modules` directories: two Git submodules for the stdlib and git dependencies and a symlink to the composer module in your home directory (`/home/tploch/projects/mfb/subprojects/puppet-composer`).

Since Puppet's module installer checks out submodules, users end up with duplicate copies of the stdlib and git modules. In addition, the symlinks cause this error on the Puppet console:

```
Warning: Symlinks in modules are unsupported. Please investigate symlink tPl0ch-composer-1.3.5/spec/fixtures/modules/composer->/home/tploch/projects/mfb/subprojects/puppet-composer.
```

**Comment by AlmogBaku** [comment]
same for me

**Comment by tPl0ch** [comment]
The new 1.3.6 version should be fixed. Sorry for that inconvinience :)
