### ISSUE TITLE
Cannot understand environment setting "COMPOSER_HOME="

### ISSUE THREAD

**Issue by simeonfelis** [tPl0ch/puppet-composer#95]
Using tPl0ch-composer (v1.3.7)
When running as service, composer update fails. When running puppet agent -t , composer update succeeds.

I enabled debug output for the service:
```
cat /etc/default/puppet
# Defaults for puppet - sourced by /etc/init.d/puppet

# Enable puppet agent service?
# Setting this to "yes" allows the puppet agent service to run.
# Setting this to "no" keeps the puppet agent service from running.
START=yes

# Startup options
#DAEMON_OPTS=""
DAEMON_OPTS="--logdest /var/log/puppet/puppet.log --verbose"
```

I could see the line with a warning containing
`Cannot understand environment setting "COMPOSER_HOME="`

The problem is that it should be COMPOSER_HOME=/root and not empty. The problematic code is in modules/composer/manifests/exec.pp:
cat modules/composer/manifests/exec.pp 
```
[...]
  Exec {
    path        => "/bin:/usr/bin/:/sbin:/usr/sbin:${composer::target_dir}",
    #environment => ["COMPOSER_HOME=${composer::composer_home}", "COMPOSER_PROCESS_TIMEOUT=${m_timeout}"],
    environment => ["COMPOSER_HOME='/root'", "COMPOSER_PROCESS_TIMEOUT=${m_timeout}"],
    user        => $user,
    timeout     => $timeout
  }
[...]
```

With this change, composer update succeeds when running as service.

So `COMPOSER_HOME=${composer::composer_home}` cannot evaluate `${composer::composer_home}`. Looks like a puppet scope problem. I tried to see if I can resolve it correctly to provide a patch, but I gave up after 1h. Now I'm using this ugly hardcoded bugfix.

**Comment by mattclegg** [comment]
composer_home should return the current users $HOME environment variable.

If you want to override this then I suggest setting `composer_home` as one of the parameters when you reference composer.
